//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilDev.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilDev.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-{{1}}.backup.
        /// </summary>
        internal static string BackupFormat {
            get {
                return ResourceManager.GetString("BackupFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;1Q&gt;[[h;t7%&amp;i9kgW,NKg,ZT;I(x:xcQ5)^I.
        /// </summary>
        internal static string C91Path {
            get {
                return ResourceManager.GetString("C91Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;1Q&gt;[[h;t7%&amp;i9kgW,O3v)R1;%`n58cj0OIhZ.
        /// </summary>
        internal static string C91PathN {
            get {
                return ResourceManager.GetString("C91PathN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DimEmptyImage {
            get {
                object obj = ResourceManager.GetObject("DimEmptyImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %CurrentDir%
        ///%CurrentDir%\Bin
        ///%CurrentDir%\Binaries
        ///%ApplicationData%\References
        ///%ApplicationData%\References\dotNet4\irrKlang
        ///%LocalApplicationData%\References
        ///%LocalApplicationData%\References\dotNet4\irrKlang
        ///%CommonApplicationData%\References
        ///%CommonApplicationData%\References\dotNet4\irrKlang
        ///%UserProfile%\References
        ///%UserProfile%\References\dotNet4\irrKlang
        ///%MyDocuments%\References
        ///%MyDocuments%\References\dotNet4\irrKlang
        ///%MyDocuments%\Visual Studio\References
        ///%MyDocuments%\Visual Studi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReferenceDirs {
            get {
                return ResourceManager.GetString("ReferenceDirs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SearchImage {
            get {
                object obj = ResourceManager.GetObject("SearchImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SizeGripImage {
            get {
                object obj = ResourceManager.GetObject("SizeGripImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %TEMP%\tmp-{0}.
        /// </summary>
        internal static string TempDirFormat {
            get {
                return ResourceManager.GetString("TempDirFormat", resourceCulture);
            }
        }
    }
}
